package bitMex_api

import "time"

type RespSymbols []date

type date struct {
	Symbol                         string      `json:"symbol"`
	RootSymbol                     string      `json:"rootSymbol"`
	State                          string      `json:"state"`
	Typ                            string      `json:"typ"`
	Listing                        time.Time   `json:"listing"`
	Front                          time.Time   `json:"front"`
	Expiry                         time.Time   `json:"expiry"`
	Settle                         time.Time   `json:"settle"`
	ListedSettle                   time.Time   `json:"listedSettle"`
	RelistInterval                 interface{} `json:"relistInterval"`
	InverseLeg                     string      `json:"inverseLeg"`
	SellLeg                        string      `json:"sellLeg"`
	BuyLeg                         string      `json:"buyLeg"`
	OptionStrikePcnt               interface{} `json:"optionStrikePcnt"`
	OptionStrikeRound              interface{} `json:"optionStrikeRound"`
	OptionStrikePrice              interface{} `json:"optionStrikePrice"`
	OptionMultiplier               interface{} `json:"optionMultiplier"`
	PositionCurrency               string      `json:"positionCurrency"`
	Underlying                     string      `json:"underlying"`
	QuoteCurrency                  string      `json:"quoteCurrency"`
	UnderlyingSymbol               string      `json:"underlyingSymbol"`
	Reference                      string      `json:"reference"`
	ReferenceSymbol                string      `json:"referenceSymbol"`
	CalcInterval                   interface{} `json:"calcInterval"`
	PublishInterval                interface{} `json:"publishInterval"`
	PublishTime                    interface{} `json:"publishTime"`
	MaxOrderQty                    int64       `json:"maxOrderQty"`
	MaxPrice                       float64     `json:"maxPrice"`
	LotSize                        int         `json:"lotSize"`
	TickSize                       float64     `json:"tickSize"`
	Multiplier                     int         `json:"multiplier"`
	SettlCurrency                  string      `json:"settlCurrency"`
	UnderlyingToPositionMultiplier int         `json:"underlyingToPositionMultiplier"`
	UnderlyingToSettleMultiplier   int         `json:"underlyingToSettleMultiplier"`
	QuoteToSettleMultiplier        int         `json:"quoteToSettleMultiplier"`
	IsQuanto                       bool        `json:"isQuanto"`
	IsInverse                      bool        `json:"isInverse"`
	InitMargin                     float64     `json:"initMargin"`
	MaintMargin                    float64     `json:"maintMargin"`
	RiskLimit                      int64       `json:"riskLimit"`
	RiskStep                       int64       `json:"riskStep"`
	Limit                          float64     `json:"limit"`
	Capped                         bool        `json:"capped"`
	Taxed                          bool        `json:"taxed"`
	Deleverage                     bool        `json:"deleverage"`
	MakerFee                       float64     `json:"makerFee"`
	TakerFee                       float64     `json:"takerFee"`
	SettlementFee                  int         `json:"settlementFee"`
	InsuranceFee                   int         `json:"insuranceFee"`
	FundingBaseSymbol              string      `json:"fundingBaseSymbol"`
	FundingQuoteSymbol             string      `json:"fundingQuoteSymbol"`
	FundingPremiumSymbol           string      `json:"fundingPremiumSymbol"`
	FundingTimestamp               time.Time   `json:"fundingTimestamp"`
	FundingInterval                time.Time   `json:"fundingInterval"`
	FundingRate                    float64     `json:"fundingRate"`
	IndicativeFundingRate          float64     `json:"indicativeFundingRate"`
	RebalanceTimestamp             interface{} `json:"rebalanceTimestamp"`
	RebalanceInterval              interface{} `json:"rebalanceInterval"`
	OpeningTimestamp               time.Time   `json:"openingTimestamp"`
	ClosingTimestamp               time.Time   `json:"closingTimestamp"`
	SessionInterval                time.Time   `json:"sessionInterval"`
	PrevClosePrice                 float64     `json:"prevClosePrice"`
	LimitDownPrice                 float64     `json:"limitDownPrice"`
	LimitUpPrice                   float64     `json:"limitUpPrice"`
	BankruptLimitDownPrice         interface{} `json:"bankruptLimitDownPrice"`
	BankruptLimitUpPrice           interface{} `json:"bankruptLimitUpPrice"`
	PrevTotalVolume                int64       `json:"prevTotalVolume"`
	TotalVolume                    int64       `json:"totalVolume"`
	Volume                         int64       `json:"volume"`
	Volume24H                      int64       `json:"volume24h"`
	PrevTotalTurnover              int64       `json:"prevTotalTurnover"`
	TotalTurnover                  int64       `json:"totalTurnover"`
	Turnover                       int64       `json:"turnover"`
	Turnover24H                    int64       `json:"turnover24h"`
	HomeNotional24H                float64     `json:"homeNotional24h"`
	ForeignNotional24H             float64     `json:"foreignNotional24h"`
	PrevPrice24H                   float64     `json:"prevPrice24h"`
	Vwap                           float64     `json:"vwap"`
	HighPrice                      float64     `json:"highPrice"`
	LowPrice                       float64     `json:"lowPrice"`
	LastPrice                      float64     `json:"lastPrice"`
	LastPriceProtected             float64     `json:"lastPriceProtected"`
	LastTickDirection              string      `json:"lastTickDirection"`
	LastChangePcnt                 float64     `json:"lastChangePcnt"`
	BidPrice                       float64     `json:"bidPrice"`
	MidPrice                       float64     `json:"midPrice"`
	AskPrice                       float64     `json:"askPrice"`
	ImpactBidPrice                 float64     `json:"impactBidPrice"`
	ImpactMidPrice                 float64     `json:"impactMidPrice"`
	ImpactAskPrice                 float64     `json:"impactAskPrice"`
	HasLiquidity                   bool        `json:"hasLiquidity"`
	OpenInterest                   int64       `json:"openInterest"`
	OpenValue                      int64       `json:"openValue"`
	FairMethod                     string      `json:"fairMethod"`
	FairBasisRate                  float64     `json:"fairBasisRate"`
	FairBasis                      float64     `json:"fairBasis"`
	FairPrice                      float64     `json:"fairPrice"`
	MarkMethod                     string      `json:"markMethod"`
	MarkPrice                      float64     `json:"markPrice"`
	IndicativeTaxRate              int         `json:"indicativeTaxRate"`
	IndicativeSettlePrice          float64     `json:"indicativeSettlePrice"`
	OptionUnderlyingPrice          interface{} `json:"optionUnderlyingPrice"`
	SettledPriceAdjustmentRate     interface{} `json:"settledPriceAdjustmentRate"`
	SettledPrice                   interface{} `json:"settledPrice"`
	Timestamp                      time.Time   `json:"timestamp"`
}

type Depthdate struct {
	Symbol string  `json:"symbol"`
	Id     int64   `json:"id"`
	Side   string  `json:"side"`
	Size   float64 `json:"size"`
	Price  float64 `json:"price"`
}

type RespDepth []*Depthdate
