servers = ["nats://127.0.0.1:4222", "nats://127.0.0.1:4223"]
connection_name = "foo"
nkeys_seed = "" # 用于nats认证的nkey token
connect_timeout = "2s" # 最大连接超时时间
reconnect_wait = "2s" # 重连时间间隔
max_reconnects = 10000  # 最多重连次数，达到后彻底关闭连接
# 发送端最大发送缓冲，用于缓存连接断开时发送的消息，连接恢复后会一次性发送所有消息，
# 如果不希望发送积压的历史消息，可以设置成1避免缓存消息
reconnect_buf_size = 1 #8388608 
ping_interval = "2m" # ping间隔时间
max_pings_outstanding = 2 # 最大未回应ping数量