// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: cfg/msg.proto

package cfg

import (
	common "github.com/warmplanet/proto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CfgRspCode int32

const (
	CfgRspCode_CFG_OK           CfgRspCode = 0
	CfgRspCode_CFG_BAD_REQ      CfgRspCode = 1
	CfgRspCode_CFG_NOT_FOUND    CfgRspCode = 2
	CfgRspCode_CFG_FORBIDDEN    CfgRspCode = 3
	CfgRspCode_CFG_INTERNAL_ERR CfgRspCode = 4
)

// Enum value maps for CfgRspCode.
var (
	CfgRspCode_name = map[int32]string{
		0: "CFG_OK",
		1: "CFG_BAD_REQ",
		2: "CFG_NOT_FOUND",
		3: "CFG_FORBIDDEN",
		4: "CFG_INTERNAL_ERR",
	}
	CfgRspCode_value = map[string]int32{
		"CFG_OK":           0,
		"CFG_BAD_REQ":      1,
		"CFG_NOT_FOUND":    2,
		"CFG_FORBIDDEN":    3,
		"CFG_INTERNAL_ERR": 4,
	}
)

func (x CfgRspCode) Enum() *CfgRspCode {
	p := new(CfgRspCode)
	*p = x
	return p
}

func (x CfgRspCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CfgRspCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cfg_msg_proto_enumTypes[0].Descriptor()
}

func (CfgRspCode) Type() protoreflect.EnumType {
	return &file_cfg_msg_proto_enumTypes[0]
}

func (x CfgRspCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CfgRspCode.Descriptor instead.
func (CfgRspCode) EnumDescriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{0}
}

// 配置值的内部结构，仅供配置中心内部使用，不对外暴露
type CfgValueInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳，毫秒级
	Hash      []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`             // value的hash值，一般使用crypto hash
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`           // value值
	HisId     []byte `protobuf:"bytes,4,opt,name=hisId,proto3" json:"hisId,omitempty"`           // 历史信息表中的唯一id
}

func (x *CfgValueInternal) Reset() {
	*x = CfgValueInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgValueInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgValueInternal) ProtoMessage() {}

func (x *CfgValueInternal) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgValueInternal.ProtoReflect.Descriptor instead.
func (*CfgValueInternal) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *CfgValueInternal) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CfgValueInternal) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CfgValueInternal) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CfgValueInternal) GetHisId() []byte {
	if x != nil {
		return x.HisId
	}
	return nil
}

type CfgKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // a.b.c形式的key
	Version []byte `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // version号，使用上次rsp返回的数据对应的ver，配置中心可自由选择不同是版本方案
}

func (x *CfgKey) Reset() {
	*x = CfgKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgKey) ProtoMessage() {}

func (x *CfgKey) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgKey.ProtoReflect.Descriptor instead.
func (*CfgKey) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *CfgKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CfgKey) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

type CfgValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`           // 任意数据
	Timestamp uint64 `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 配置项的时间戳
	Version   []byte `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`       // version号，如果请求的version和配置中心一样，返回的value为空
}

func (x *CfgValue) Reset() {
	*x = CfgValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgValue) ProtoMessage() {}

func (x *CfgValue) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgValue.ProtoReflect.Descriptor instead.
func (*CfgValue) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *CfgValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CfgValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CfgValue) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

type CfgKeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`               // a.b.c形式的key
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`           // 任意数据
	Timestamp uint64 `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` //配置项的时间戳
	Version   []byte `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`       // version号，如果请求的version和配置中心一样，返回的value为空
}

func (x *CfgKeyValue) Reset() {
	*x = CfgKeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgKeyValue) ProtoMessage() {}

func (x *CfgKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgKeyValue.ProtoReflect.Descriptor instead.
func (*CfgKeyValue) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *CfgKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CfgKeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CfgKeyValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CfgKeyValue) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

// 配置请求消息
type CfgGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string    `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"` // 默认为空，区分不同的环境
	Group  string    `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`   // 配置所在分组，基于业务的分类，比如symbol,riskrule等
	Range  bool      `protobuf:"varint,3,opt,name=range,proto3" json:"range,omitempty"`  // 是否是范围查询，范围查询范围为(keys[0],keys[1])
	Keys   []*CfgKey `protobuf:"bytes,10,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *CfgGetReq) Reset() {
	*x = CfgGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgGetReq) ProtoMessage() {}

func (x *CfgGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgGetReq.ProtoReflect.Descriptor instead.
func (*CfgGetReq) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *CfgGetReq) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CfgGetReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CfgGetReq) GetRange() bool {
	if x != nil {
		return x.Range
	}
	return false
}

func (x *CfgGetReq) GetKeys() []*CfgKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// 配置响应消息
type CfgGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code CfgRspCode     `protobuf:"varint,1,opt,name=code,proto3,enum=cfg.CfgRspCode" json:"code,omitempty"`
	Msg  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Vals []*CfgKeyValue `protobuf:"bytes,10,rep,name=vals,proto3" json:"vals,omitempty"`
}

func (x *CfgGetRsp) Reset() {
	*x = CfgGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgGetRsp) ProtoMessage() {}

func (x *CfgGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgGetRsp.ProtoReflect.Descriptor instead.
func (*CfgGetRsp) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *CfgGetRsp) GetCode() CfgRspCode {
	if x != nil {
		return x.Code
	}
	return CfgRspCode_CFG_OK
}

func (x *CfgGetRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CfgGetRsp) GetVals() []*CfgKeyValue {
	if x != nil {
		return x.Vals
	}
	return nil
}

// 配置更新消息，接收方通过单调递增的sequence来识别通信层错误(消息丢失)，
// 通过prev_version来识别数据层的错误(接收方key的当前version必须等于prev_version才能更新)
type CfgUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hdr         *common.MsgHeader `protobuf:"bytes,1,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Tenant      string            `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Group       string            `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	PrevVersion []byte            `protobuf:"bytes,10,opt,name=prev_version,json=prevVersion,proto3" json:"prev_version,omitempty"` // key对应的上一个版本号，用于接收方对比是否和当前一致，不一致需要
	Kv          *CfgKeyValue      `protobuf:"bytes,11,opt,name=kv,proto3" json:"kv,omitempty"`                                      // 配置项最新内容
}

func (x *CfgUpdate) Reset() {
	*x = CfgUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cfg_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgUpdate) ProtoMessage() {}

func (x *CfgUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cfg_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgUpdate.ProtoReflect.Descriptor instead.
func (*CfgUpdate) Descriptor() ([]byte, []int) {
	return file_cfg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *CfgUpdate) GetHdr() *common.MsgHeader {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *CfgUpdate) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CfgUpdate) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CfgUpdate) GetPrevVersion() []byte {
	if x != nil {
		return x.PrevVersion
	}
	return nil
}

func (x *CfgUpdate) GetKv() *CfgKeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

var File_cfg_msg_proto protoreflect.FileDescriptor

var file_cfg_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x66, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x63, 0x66, 0x67, 0x1a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x10, 0x43, 0x66, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x69, 0x73, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x68, 0x69, 0x73, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x06, 0x43, 0x66, 0x67, 0x4b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x58,
	0x0a, 0x08, 0x43, 0x66, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x0b, 0x43, 0x66, 0x67, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x06, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x09, 0x43, 0x66, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x66, 0x67, 0x2e, 0x43, 0x66, 0x67,
	0x4b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x68, 0x0a, 0x09, 0x43, 0x66, 0x67,
	0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x66, 0x67, 0x2e, 0x43, 0x66, 0x67, 0x52, 0x73,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x24, 0x0a,
	0x04, 0x76, 0x61, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x66,
	0x67, 0x2e, 0x43, 0x66, 0x67, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x76,
	0x61, 0x6c, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x09, 0x43, 0x66, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x03, 0x68, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x03, 0x68, 0x64, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x66, 0x67, 0x2e, 0x43, 0x66, 0x67, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02,
	0x6b, 0x76, 0x2a, 0x65, 0x0a, 0x0a, 0x43, 0x66, 0x67, 0x52, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x46, 0x47, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x46, 0x47, 0x5f, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x46, 0x47, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x43, 0x46, 0x47, 0x5f, 0x46, 0x4f, 0x52, 0x42, 0x49, 0x44, 0x44, 0x45,
	0x4e, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x46, 0x47, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x10, 0x04, 0x42, 0x3a, 0x0a, 0x14, 0x77, 0x61, 0x72,
	0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x66,
	0x67, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61,
	0x72, 0x6d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x2f, 0x63, 0x66, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cfg_msg_proto_rawDescOnce sync.Once
	file_cfg_msg_proto_rawDescData = file_cfg_msg_proto_rawDesc
)

func file_cfg_msg_proto_rawDescGZIP() []byte {
	file_cfg_msg_proto_rawDescOnce.Do(func() {
		file_cfg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_cfg_msg_proto_rawDescData)
	})
	return file_cfg_msg_proto_rawDescData
}

var file_cfg_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cfg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cfg_msg_proto_goTypes = []interface{}{
	(CfgRspCode)(0),          // 0: cfg.CfgRspCode
	(*CfgValueInternal)(nil), // 1: cfg.CfgValueInternal
	(*CfgKey)(nil),           // 2: cfg.CfgKey
	(*CfgValue)(nil),         // 3: cfg.CfgValue
	(*CfgKeyValue)(nil),      // 4: cfg.CfgKeyValue
	(*CfgGetReq)(nil),        // 5: cfg.CfgGetReq
	(*CfgGetRsp)(nil),        // 6: cfg.CfgGetRsp
	(*CfgUpdate)(nil),        // 7: cfg.CfgUpdate
	(*common.MsgHeader)(nil), // 8: MsgHeader
}
var file_cfg_msg_proto_depIdxs = []int32{
	2, // 0: cfg.CfgGetReq.keys:type_name -> cfg.CfgKey
	0, // 1: cfg.CfgGetRsp.code:type_name -> cfg.CfgRspCode
	4, // 2: cfg.CfgGetRsp.vals:type_name -> cfg.CfgKeyValue
	8, // 3: cfg.CfgUpdate.hdr:type_name -> MsgHeader
	4, // 4: cfg.CfgUpdate.kv:type_name -> cfg.CfgKeyValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cfg_msg_proto_init() }
func file_cfg_msg_proto_init() {
	if File_cfg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cfg_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgValueInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgKeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cfg_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cfg_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cfg_msg_proto_goTypes,
		DependencyIndexes: file_cfg_msg_proto_depIdxs,
		EnumInfos:         file_cfg_msg_proto_enumTypes,
		MessageInfos:      file_cfg_msg_proto_msgTypes,
	}.Build()
	File_cfg_msg_proto = out.File
	file_cfg_msg_proto_rawDesc = nil
	file_cfg_msg_proto_goTypes = nil
	file_cfg_msg_proto_depIdxs = nil
}
